[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
optimizer = true
optimizer_runs = 2500
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_API_KEY}" }
base = { key = "${ETHERSCAN_BASE_API_KEY}" }

[doc]
out = "foundry-docs/"
title = "Euler Swap Contracts Documentation"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
